# Generated by Django 2.2.15 on 2020-08-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cv',
        ),
    ]
