# Generated by Django 2.2.15 on 2020-09-01 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200901_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='time',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='time',
        ),
        migrations.AddField(
            model_name='education',
            name='time_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='time_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='time_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='time_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='time_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='time_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
