# Generated by Django 2.2.15 on 2020-09-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200901_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
