# Generated by Django 2.2.15 on 2020-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20200901_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('P', 'Programming'), ('M', 'Markup'), ('TT', 'Technologies and Tools'), ('L', 'Languages')], default='Programming', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='time_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
