# Generated by Django 2.2.15 on 2020-09-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200901_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='education',
            name='time_end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='time_start',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_start',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Markup', 'Markup'), ('Technologies and Tools', 'Technologies and Tools'), ('Languages', 'Languages')], max_length=25),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='time_end',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='time_start',
            field=models.CharField(max_length=20),
        ),
    ]
